package dao;
// Generated 15/04/2018 01:22:22 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name="area"
    ,catalog="cocoedb"
    , uniqueConstraints = {@UniqueConstraint(columnNames="code"), @UniqueConstraint(columnNames="name")} 
)
public class Area  implements java.io.Serializable {


    private Integer id;
    private String name;
    private String code;
    private Date createdDate;

    public Area() {
    }

    public Area(String name, String code, Date createdDate) {
       this.name = name;
       this.code = code;
       this.createdDate = createdDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="code", unique=true, nullable=false, length=12)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdDate", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


