package dao;
// Generated Apr 17, 2018 9:02:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="client"
    ,catalog="cocoedb"
)
public class Client  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String name;
     private String lastName;
     private boolean active;
     private int areaid;
     private String direction;
     private Date createdDate;
     private Date lastBillingDate;

    public Client() {
    }

    public Client(String code, String name, String lastName, boolean active, int areaid, String direction, Date createdDate, Date lastBillingDate) {
       this.code = code;
       this.name = name;
       this.lastName = lastName;
       this.active = active;
       this.areaid = areaid;
       this.direction = direction;
       this.createdDate = createdDate;
       this.lastBillingDate = lastBillingDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="code", nullable=false, length=12)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="lastName", nullable=false, length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }

    
    @Column(name="areaid", nullable=false)
    public int getAreaid() {
        return this.areaid;
    }
    
    public void setAreaid(int areaid) {
        this.areaid = areaid;
    }

    
    @Column(name="direction", nullable=false, length=512)
    public String getDirection() {
        return this.direction;
    }
    
    public void setDirection(String direction) {
        this.direction = direction;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdDate", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastBillingDate", nullable=false, length=19)
    public Date getLastBillingDate() {
        return this.lastBillingDate;
    }
    
    public void setLastBillingDate(Date lastBillingDate) {
        this.lastBillingDate = lastBillingDate;
    }




}


