package dao;
// Generated Apr 17, 2018 9:02:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clientmetering generated by hbm2java
 */
@Entity
@Table(name="clientmetering"
    ,catalog="cocoedb"
)
public class Clientmetering  implements java.io.Serializable {


     private Integer id;
     private int meterSessionId;
     private int clientId;
     private long amount;
     private int uomId;
     private Date meteringDate;
     private boolean billed;
     private Date createdDate;

    public Clientmetering() {
    }

    public Clientmetering(int meterSessionId, int clientId, long amount, int uomId, Date meteringDate, boolean billed, Date createdDate) {
       this.meterSessionId = meterSessionId;
       this.clientId = clientId;
       this.amount = amount;
       this.uomId = uomId;
       this.meteringDate = meteringDate;
       this.billed = billed;
       this.createdDate = createdDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="meterSessionId", nullable=false)
    public int getMeterSessionId() {
        return this.meterSessionId;
    }
    
    public void setMeterSessionId(int meterSessionId) {
        this.meterSessionId = meterSessionId;
    }

    
    @Column(name="clientId", nullable=false)
    public int getClientId() {
        return this.clientId;
    }
    
    public void setClientId(int clientId) {
        this.clientId = clientId;
    }

    
    @Column(name="amount", nullable=false, precision=10, scale=0)
    public long getAmount() {
        return this.amount;
    }
    
    public void setAmount(long amount) {
        this.amount = amount;
    }

    
    @Column(name="uomId", nullable=false)
    public int getUomId() {
        return this.uomId;
    }
    
    public void setUomId(int uomId) {
        this.uomId = uomId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="meteringDate", nullable=false, length=19)
    public Date getMeteringDate() {
        return this.meteringDate;
    }
    
    public void setMeteringDate(Date meteringDate) {
        this.meteringDate = meteringDate;
    }

    
    @Column(name="billed", nullable=false)
    public boolean isBilled() {
        return this.billed;
    }
    
    public void setBilled(boolean billed) {
        this.billed = billed;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdDate", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


