package dao;
// Generated 14/04/2018 12:43:29 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String name;
     private String lastName;
     private boolean active;
     private int areaid;
     private String direction;
     private Date createdDate;
     private Date lastBillingDate;

    public Client() {
    }

    public Client(String code, String name, String lastName, boolean active, int areaid, String direction, Date createdDate, Date lastBillingDate) {
       this.code = code;
       this.name = name;
       this.lastName = lastName;
       this.active = active;
       this.areaid = areaid;
       this.direction = direction;
       this.createdDate = createdDate;
       this.lastBillingDate = lastBillingDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public int getAreaid() {
        return this.areaid;
    }
    
    public void setAreaid(int areaid) {
        this.areaid = areaid;
    }
    public String getDirection() {
        return this.direction;
    }
    
    public void setDirection(String direction) {
        this.direction = direction;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getLastBillingDate() {
        return this.lastBillingDate;
    }
    
    public void setLastBillingDate(Date lastBillingDate) {
        this.lastBillingDate = lastBillingDate;
    }




}


