package dao;
// Generated Apr 17, 2018 9:02:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Metersessionuser generated by hbm2java
 */
@Entity
@Table(name="metersessionuser"
    ,catalog="cocoedb"
)
public class Metersessionuser  implements java.io.Serializable {


     private Integer id;
     private int userid;
     private int metersessionid;
     private Date createdDate;

    public Metersessionuser() {
    }

    public Metersessionuser(int userid, int metersessionid, Date createdDate) {
       this.userid = userid;
       this.metersessionid = metersessionid;
       this.createdDate = createdDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="userid", nullable=false)
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }

    
    @Column(name="metersessionid", nullable=false)
    public int getMetersessionid() {
        return this.metersessionid;
    }
    
    public void setMetersessionid(int metersessionid) {
        this.metersessionid = metersessionid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdDate", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


