package dao;
// Generated Apr 17, 2018 9:02:26 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Settings generated by hbm2java
 */
@Entity
@Table(name="settings"
    ,catalog="cocoedb"
)
public class Settings  implements java.io.Serializable {


     private String settingKey;
     private String settingValue;

    public Settings() {
    }

    public Settings(String settingKey, String settingValue) {
       this.settingKey = settingKey;
       this.settingValue = settingValue;
    }
   
     @Id 

    
    @Column(name="settingKey", unique=true, nullable=false, length=50)
    public String getSettingKey() {
        return this.settingKey;
    }
    
    public void setSettingKey(String settingKey) {
        this.settingKey = settingKey;
    }

    
    @Column(name="settingValue", nullable=false, length=2018)
    public String getSettingValue() {
        return this.settingValue;
    }
    
    public void setSettingValue(String settingValue) {
        this.settingValue = settingValue;
    }




}


