package dao;
// Generated 14/04/2018 12:43:29 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String userName;
     private String passwordHash;
     private String name;
     private String lastName;
     private Date createdDate;
     private Date lastLoginDate;

    public User() {
    }

	
    public User(String userName, String passwordHash, String name, String lastName, Date createdDate) {
        this.userName = userName;
        this.passwordHash = passwordHash;
        this.name = name;
        this.lastName = lastName;
        this.createdDate = createdDate;
    }
    public User(String userName, String passwordHash, String name, String lastName, Date createdDate, Date lastLoginDate) {
       this.userName = userName;
       this.passwordHash = passwordHash;
       this.name = name;
       this.lastName = lastName;
       this.createdDate = createdDate;
       this.lastLoginDate = lastLoginDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPasswordHash() {
        return this.passwordHash;
    }
    
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getLastLoginDate() {
        return this.lastLoginDate;
    }
    
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }




}


