package dao;
// Generated Apr 17, 2018 9:02:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="cocoedb"
)
public class User  implements java.io.Serializable {


     private Integer id;
     private String userName;
     private String passwordHash;
     private String name;
     private String lastName;
     private String role;
     private Date createdDate;
     private Date lastLoginDate;

    public User() {
    }

	
    public User(String userName, String passwordHash, String name, String lastName, String role, Date createdDate) {
        this.userName = userName;
        this.passwordHash = passwordHash;
        this.name = name;
        this.lastName = lastName;
        this.role = role;
        this.createdDate = createdDate;
    }
    public User(String userName, String passwordHash, String name, String lastName, String role, Date createdDate, Date lastLoginDate) {
       this.userName = userName;
       this.passwordHash = passwordHash;
       this.name = name;
       this.lastName = lastName;
       this.role = role;
       this.createdDate = createdDate;
       this.lastLoginDate = lastLoginDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="userName", nullable=false, length=50)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="passwordHash", nullable=false)
    public String getPasswordHash() {
        return this.passwordHash;
    }
    
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="lastName", nullable=false, length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="role", nullable=false, length=15)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdDate", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastLoginDate", length=19)
    public Date getLastLoginDate() {
        return this.lastLoginDate;
    }
    
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }




}


